apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mydb
  name: mydb
spec:
  containers:
  - env:
    - name: MYSQL_ROOT_PASSWORD
      value: {{ .Values.mysql_root_password }}
    - name: MYSQL_DATABASE
      value: {{ .Values.mysql_database }}
    - name: MYSQL_USER
      value: {{ .Values.mysql_user }}
    - name: MYSQL_PASSWORD
      value: {{ .Values.mysql_password }}
    image: mysql:5.7
    name: mydb
